### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by W2L** [youzan/YouzanMobileSDK-Android#32]
compileSdkVersion: 29
minSdkVersion: 19
targetSdkVersion: 29
x5 sdk：tbs_sdk_thirdapp_v4.3.0.3_43903_sharewithdownloadwithfile_withoutGame_obfs_20200402_121309

打开有赞网页时提示这个错误

W/System.err: java.lang.NoSuchMethodError: No interface method onNotifyScreenStatus(I)V in class Lcom/tencent/smtt/export/external/extension/interfaces/IX5WebViewClientExtension; or its super classes (declaration of 'com.tencent.smtt.export.external.extension.interfaces.IX5WebViewClientExtension' appears in /data/app/cn.babyfs.android-eYVIOiEPq1rFp1P-T9kbig==/base.apk!classes3.dex)
    at com.tencent.smtt.webkit.WebViewChromiumExtension.s(TbsJavaCore:4756)
    at org.chromium.tencent.TencentAwContent.notifyScreenStatus(TbsJavaCore:649)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:336)
    at android.os.Looper.loop(Looper.java:181)
    at android.app.ActivityThread.main(ActivityThread.java:7520)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Mynameislyc** [comment]
I caught this exception. How can I solve it？

**Comment by zhuiyue132** [comment]
+1
