### ISSUE TITLE
SDK  loginout时奔溃

### ISSUE THREAD

**Issue by qq309213760** [youzan/YouzanMobileSDK-Android#35]
java.lang.IllegalStateException: You Should Init with A Valid SDK Adapter,YouzanBasicSDKAdapter for basic sdk, and YouzanHybridSDKAdapter for native sdk
at com.youzan.androidsdk.YouzanSDK.ˊ(YouzanSDK.java:37)
at com.youzan.androidsdk.YouzanSDK.userLogout(YouzanSDK.java:124)

**Comment by ddsyb** [comment]
一样的问题

**Comment by ddsyb** [comment]
是不是没有初始化成功

**Comment by ddsyb** [comment]
是不是没有初始化成功
