### ISSUE TITLE
Didn't find class "com.youzan.androidsdk.basic.YouzanBrowser"

### ISSUE THREAD

**Issue by ArnoFrost** [youzan/YouzanMobileSDK-Android#7]
`09-14 13:59:18.091 19911-20597/com.ileja.lite E/chromium: [ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
09-14 13:59:21.903 19911-19911/com.ileja.lite E/Fatal Error ==>: Didn't find class "com.youzan.androidsdk.basic.YouzanBrowser" on path: DexPathList[[zip file "/data/app/com.ileja.lite-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ileja.lite-1/lib/arm, /data/app/com.ileja.lite-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
09-14 13:59:21.990 19911-19911/com.ileja.lite E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ileja.lite, PID: 19911
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ileja.lite/com.ileja.carrobot.youzan.YouzanActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.youzan.androidsdk.basic.YouzanBrowser
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2514)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
        at android.app.ActivityThread.access$1100(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.youzan.androidsdk.basic.YouzanBrowser
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.ileja.carrobot.youzan.WebViewFragment.onCreateView(WebViewFragment.java:49)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
        at android.app.Activity.performStart(Activity.java:6372)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2477)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.youzan.androidsdk.basic.YouzanBrowser
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:842)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
        at com.ileja.carrobot.youzan.WebViewFragment.onCreateView(WebViewFragment.java:49) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2354) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221) 
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171) 
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238) 
        at android.app.Activity.performStart(Activity.java:6372) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2477) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.youzan.androidsdk.basic.YouzanBrowser" on path: DexPathList[[zip file "/data/app/com.ileja.lite-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ileja.lite-1/lib/arm, /data/app/com.ileja.lite-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    	at android.view.LayoutInflater.createView(LayoutInflater.java
`

运行后这样 ndk里我也加了 armeabi-v7a处理了

**Comment by EnternalRain** [comment]
com.youzan.androidsdk.basic.YouzanBrowser这个类是基于原生WebView的Basic版本。如果引入的x5内核版本，应该改成com.youzan.androidsdkx5.YouzanBrowser
